In [118]:
import pandas as pd
import os 
import sys
cwd = os.getcwd()

pd.set_option('display.max_rows', 30)
pd.set_option('display.max_columns', None)

In [119]:
import os

fpl_path = os.path.join(cwd, '..', '..', 'data', 'history', 'merged_gw_2324.csv')
team_path = os.path.join(cwd, '..', '..', 'data', 'history', 'teams_2324.csv')
fixture_path= os.path.join(cwd, '..', '..', 'data', 'history', 'fixtures_2324.csv')
data_folder=os.path.join(cwd, '..', '..', 'data', 'history')
df_player = pd.read_csv(fpl_path)
df_team=pd.read_csv(team_path)
df_fixture=pd.read_csv(fixture_path)

In [120]:
df_player

,name,position,team,xP,assists,bonus,bps,clean_sheets,creativity,element,expected_assists,expected_goal_involvements,expected_goals,expected_goals_conceded,fixture,goals_conceded,goals_scored,ict_index,influence,kickoff_time,minutes,opponent_team,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,starts,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,Femi Seriki,DEF,Sheffield Utd,0.5,0,0,0,0,0.0,653,0.00,0.00,0.00,0.00,7,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,8,0,0,0,0,1,0,0,0,1,0,0.0,0,0,0,0,40,True,0,1
1,Jack Hinshelwood,MID,Brighton,1.5,0,0,0,0,0.0,621,0.00,0.00,0.00,0.00,4,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,12,0,0,0,0,1,0,822,0,1,4,0.0,0,0,0,0,45,True,0,1
2,Jadon Sancho,MID,Man Utd,3.0,0,0,4,0,11.3,397,0.05,0.05,0.00,1.08,10,0,0,2.3,3.8,2023-08-14T19:00:00Z,22,20,0,0,0,0,1,0,83993,0,0,1,8.0,1,0,0,0,70,True,0,1
3,Rhys Norrington-Davies,DEF,Sheffield Utd,0.1,0,0,0,0,0.0,487,0.00,0.00,0.00,0.00,7,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,8,0,0,0,0,1,0,6456,0,1,0,0.0,0,0,0,0,40,True,0,1
4,Vitaly Janelt,MID,Brentford,2.1,0,0,6,0,11.5,105,0.01,0.03,0.02,1.26,8,2,0,4.3,14.6,2023-08-13T13:00:00Z,90,18,0,0,0,0,1,0,6508,1,2,2,17.0,2,0,0,0,55,True,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29720,Kyle Walker,DEF,Man City,7.5,0,0,15,0,11.6,369,0.06,0.06,0.00,0.36,379,1,0,3.2,20.6,2024-05-19T15:00:00Z,90,19,0,0,0,0,38,0,1638831,1,1,3,0.0,2,-3560,44071,47631,55,True,0,38
29721,Jacob Brown,FWD,Luton,0.0,0,0,0,0,0.0,631,0.00,0.00,0.00,0.00,378,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,10,0,0,0,0,38,0,11589,0,4,2,0.0,0,86,216,130,49,True,0,38
29722,Vicente Guaita,GK,Crystal Palace,0.0,0,0,0,0,0.0,227,0.00,0.00,0.00,0.00,376,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,2,0,0,0,0,38,0,18062,0,0,5,0.0,0,-120,0,120,44,True,0,38
29723,Braian Ojeda Rodríguez,MID,Nott'm Forest,0.0,0,0,0,0,0.0,459,0.00,0.00,0.00,0.00,374,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,6,0,0,0,0,38,0,182,0,2,1,0.0,0,-1,0,1,45,False,0,38
29724,Mads Bech Sørensen,DEF,Brentford,0.0,0,0,0,0,0.0,93,0.00,0.00,0.00,0.00,372,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,15,0,0,0,0,38,0,7260,0,4,2,0.0,0,-65,0,65,40,True,0,38

In [121]:
df_player = df_player.rename(columns={
    'name': 'Player',
    'position': 'Pos',
    'team': 'Team_player',
    'xP': 'xP',
    'assists': 'A',
    'bonus': 'B',
    'bps': 'BPS',
    'clean_sheets': 'CS',
    'creativity': 'C',
    'element': 'element',
    'expected_assists': 'xA',
    'expected_goal_involvements': 'xGI',
    'expected_goals': 'xG',
    'expected_goals_conceded': 'xGC',
    'fixture': 'fixture',
    'goals_conceded': 'GC',
    'goals_scored': 'GS',
    'ict_index': 'ICT',
    'influence': 'I',
    'kickoff_time': 'kickoff_time',
    'minutes': 'Mins',
    'opponent_team': 'vs',
    'own_goals': 'OG',
    'penalties_missed': 'Pen_Miss',
    'penalties_saved': 'Pen_Save',
    'red_cards': 'RC',
    'round': 'round',
    'saves': 'S',
    'selected': 'SB',
    'starts': 'starts',
    'team_a_score': 'team_a_score',
    'team_h_score': 'team_h_score',
    'threat': 'T',
    'total_points': 'Pts',
    'transfers_balance': 'transfers_balance',
    'transfers_in': 'Tran_In',
    'transfers_out': 'Tran_Out',
    'value': 'Price',
    'was_home': 'was_home',
    'yellow_cards': 'YC'
})

In [122]:
df_player['season']=2324

In [123]:
df_player = df_player.drop(['xP', 'element', 'fixture', 'starts', 'transfers_balance','round'], axis=1)

In [124]:
df_player

,Player,Pos,Team_player,A,B,BPS,CS,C,xA,xGI,xG,xGC,GC,GS,ICT,I,kickoff_time,Mins,vs,OG,Pen_Miss,Pen_Save,RC,S,SB,team_a_score,team_h_score,T,Pts,Tran_In,Tran_Out,Price,was_home,YC,GW,season
0,Femi Seriki,DEF,Sheffield Utd,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,8,0,0,0,0,0,0,1,0,0.0,0,0,0,40,True,0,1,2324
1,Jack Hinshelwood,MID,Brighton,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,12,0,0,0,0,0,822,1,4,0.0,0,0,0,45,True,0,1,2324
2,Jadon Sancho,MID,Man Utd,0,0,4,0,11.3,0.05,0.05,0.00,1.08,0,0,2.3,3.8,2023-08-14T19:00:00Z,22,20,0,0,0,0,0,83993,0,1,8.0,1,0,0,70,True,0,1,2324
3,Rhys Norrington-Davies,DEF,Sheffield Utd,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,8,0,0,0,0,0,6456,1,0,0.0,0,0,0,40,True,0,1,2324
4,Vitaly Janelt,MID,Brentford,0,0,6,0,11.5,0.01,0.03,0.02,1.26,2,0,4.3,14.6,2023-08-13T13:00:00Z,90,18,0,0,0,0,0,6508,2,2,17.0,2,0,0,55,True,0,1,2324
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29720,Kyle Walker,DEF,Man City,0,0,15,0,11.6,0.06,0.06,0.00,0.36,1,0,3.2,20.6,2024-05-19T15:00:00Z,90,19,0,0,0,0,0,1638831,1,3,0.0,2,44071,47631,55,True,0,38,2324
29721,Jacob Brown,FWD,Luton,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,10,0,0,0,0,0,11589,4,2,0.0,0,216,130,49,True,0,38,2324
29722,Vicente Guaita,GK,Crystal Palace,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,2,0,0,0,0,0,18062,0,5,0.0,0,0,120,44,True,0,38,2324
29723,Braian Ojeda Rodríguez,MID,Nott'm Forest,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,6,0,0,0,0,0,182,2,1,0.0,0,0,1,45,False,0,38,2324
29724,Mads Bech Sørensen,DEF,Brentford,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,15,0,0,0,0,0,7260,4,2,0.0,0,0,65,40,True,0,38,2324

In [125]:
df_player = df_player.merge(df_team[['id', 'name']], how='left', left_on='Team_player', right_on='name')

In [126]:
df_player

,Player,Pos,Team_player,A,B,BPS,CS,C,xA,xGI,xG,xGC,GC,GS,ICT,I,kickoff_time,Mins,vs,OG,Pen_Miss,Pen_Save,RC,S,SB,team_a_score,team_h_score,T,Pts,Tran_In,Tran_Out,Price,was_home,YC,GW,season,id,name
0,Femi Seriki,DEF,Sheffield Utd,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,8,0,0,0,0,0,0,1,0,0.0,0,0,0,40,True,0,1,2324,17,Sheffield Utd
1,Jack Hinshelwood,MID,Brighton,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,12,0,0,0,0,0,822,1,4,0.0,0,0,0,45,True,0,1,2324,5,Brighton
2,Jadon Sancho,MID,Man Utd,0,0,4,0,11.3,0.05,0.05,0.00,1.08,0,0,2.3,3.8,2023-08-14T19:00:00Z,22,20,0,0,0,0,0,83993,0,1,8.0,1,0,0,70,True,0,1,2324,14,Man Utd
3,Rhys Norrington-Davies,DEF,Sheffield Utd,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,8,0,0,0,0,0,6456,1,0,0.0,0,0,0,40,True,0,1,2324,17,Sheffield Utd
4,Vitaly Janelt,MID,Brentford,0,0,6,0,11.5,0.01,0.03,0.02,1.26,2,0,4.3,14.6,2023-08-13T13:00:00Z,90,18,0,0,0,0,0,6508,2,2,17.0,2,0,0,55,True,0,1,2324,4,Brentford
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29720,Kyle Walker,DEF,Man City,0,0,15,0,11.6,0.06,0.06,0.00,0.36,1,0,3.2,20.6,2024-05-19T15:00:00Z,90,19,0,0,0,0,0,1638831,1,3,0.0,2,44071,47631,55,True,0,38,2324,13,Man City
29721,Jacob Brown,FWD,Luton,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,10,0,0,0,0,0,11589,4,2,0.0,0,216,130,49,True,0,38,2324,12,Luton
29722,Vicente Guaita,GK,Crystal Palace,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,2,0,0,0,0,0,18062,0,5,0.0,0,0,120,44,True,0,38,2324,8,Crystal Palace
29723,Braian Ojeda Rodríguez,MID,Nott'm Forest,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,6,0,0,0,0,0,182,2,1,0.0,0,0,1,45,False,0,38,2324,16,Nott'm Forest
29724,Mads Bech Sørensen,DEF,Brentford,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,15,0,0,0,0,0,7260,4,2,0.0,0,0,65,40,True,0,38,2324,4,Brentford

In [127]:
# Merge for home games
merged_home = pd.merge(
    df_player[df_player['was_home'] == True],  # Filter for home games
    df_fixture[['event', 'team_h', 'team_a', 'team_h_difficulty', 'team_a_difficulty']],
    left_on=['id', 'vs'],  # 'team' is the player's team, 'vs' is the opponent team
    right_on=['team_h', 'team_a'],  # Join home team ('team_h') and away team ('team_a')
    how='left'
)

# Merge for away games
merged_away = pd.merge(
    df_player[df_player['was_home'] == False],  # Filter for away games
    df_fixture[['event', 'team_h', 'team_a', 'team_h_difficulty', 'team_a_difficulty']],
    left_on=['id', 'vs'],  # 'team' is the player's team, 'vs' is the opponent team
    right_on=['team_a', 'team_h'],  # Join away team ('team_a') and home team ('team_h')
    how='left'
)
# Combine both home and away merges
final_merged = pd.concat([merged_home, merged_away], ignore_index=True)

In [128]:
final_merged

,Player,Pos,Team_player,A,B,BPS,CS,C,xA,xGI,xG,xGC,GC,GS,ICT,I,kickoff_time,Mins,vs,OG,Pen_Miss,Pen_Save,RC,S,SB,team_a_score,team_h_score,T,Pts,Tran_In,Tran_Out,Price,was_home,YC,GW,season,id,name,event,team_h,team_a,team_h_difficulty,team_a_difficulty
0,Femi Seriki,DEF,Sheffield Utd,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,8,0,0,0,0,0,0,1,0,0.0,0,0,0,40,True,0,1,2324,17,Sheffield Utd,1,17,8,2,2
1,Jack Hinshelwood,MID,Brighton,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,12,0,0,0,0,0,822,1,4,0.0,0,0,0,45,True,0,1,2324,5,Brighton,1,5,12,2,3
2,Jadon Sancho,MID,Man Utd,0,0,4,0,11.3,0.05,0.05,0.00,1.08,0,0,2.3,3.8,2023-08-14T19:00:00Z,22,20,0,0,0,0,0,83993,0,1,8.0,1,0,0,70,True,0,1,2324,14,Man Utd,1,14,20,2,4
3,Rhys Norrington-Davies,DEF,Sheffield Utd,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,8,0,0,0,0,0,6456,1,0,0.0,0,0,0,40,True,0,1,2324,17,Sheffield Utd,1,17,8,2,2
4,Vitaly Janelt,MID,Brentford,0,0,6,0,11.5,0.01,0.03,0.02,1.26,2,0,4.3,14.6,2023-08-13T13:00:00Z,90,18,0,0,0,0,0,6508,2,2,17.0,2,0,0,55,True,0,1,2324,4,Brentford,1,4,18,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29720,Wesley Okoduwa,DEF,Wolves,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,11,0,0,0,0,0,2204,0,2,0.0,0,414,145,40,False,0,38,2324,20,Wolves,38,11,20,2,5
29721,Kevin Mbabu,DEF,Fulham,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,12,0,0,0,0,0,17658,4,2,0.0,0,0,127,40,False,0,38,2324,10,Fulham,38,12,10,2,2
29722,Tyrell Malacia,DEF,Man Utd,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,5,0,0,0,0,0,2343,2,0,0.0,0,44,21,43,False,0,38,2324,14,Man Utd,38,5,14,3,3
29723,Daniel Gore,MID,Man Utd,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,5,0,0,0,0,0,575,2,0,0.0,0,0,3,45,False,0,38,2324,14,Man Utd,38,5,14,3,3
29724,Braian Ojeda Rodríguez,MID,Nott'm Forest,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,6,0,0,0,0,0,182,2,1,0.0,0,0,1,45,False,0,38,2324,16,Nott'm Forest,38,6,16,2,2

In [129]:
final_merged['Team_fdr'] = final_merged.apply(
    lambda row: row['team_h_difficulty'] if row['was_home'] else row['team_a_difficulty'], axis=1
)
final_merged['opponent_fdr'] = final_merged.apply(
    lambda row: row['team_a_difficulty'] if row['was_home'] else row['team_h_difficulty'], axis=1
)

# Step 3: Drop the columns from df_fixture that are no longer needed
merged_fdr = final_merged.drop(columns=['team_a', 'team_h_difficulty', 'team_a_difficulty','id','name','event','team_h'])

In [130]:
merged_fdr

,Player,Pos,Team_player,A,B,BPS,CS,C,xA,xGI,xG,xGC,GC,GS,ICT,I,kickoff_time,Mins,vs,OG,Pen_Miss,Pen_Save,RC,S,SB,team_a_score,team_h_score,T,Pts,Tran_In,Tran_Out,Price,was_home,YC,GW,season,Team_fdr,opponent_fdr
0,Femi Seriki,DEF,Sheffield Utd,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,8,0,0,0,0,0,0,1,0,0.0,0,0,0,40,True,0,1,2324,2,2
1,Jack Hinshelwood,MID,Brighton,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,12,0,0,0,0,0,822,1,4,0.0,0,0,0,45,True,0,1,2324,2,3
2,Jadon Sancho,MID,Man Utd,0,0,4,0,11.3,0.05,0.05,0.00,1.08,0,0,2.3,3.8,2023-08-14T19:00:00Z,22,20,0,0,0,0,0,83993,0,1,8.0,1,0,0,70,True,0,1,2324,2,4
3,Rhys Norrington-Davies,DEF,Sheffield Utd,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,8,0,0,0,0,0,6456,1,0,0.0,0,0,0,40,True,0,1,2324,2,2
4,Vitaly Janelt,MID,Brentford,0,0,6,0,11.5,0.01,0.03,0.02,1.26,2,0,4.3,14.6,2023-08-13T13:00:00Z,90,18,0,0,0,0,0,6508,2,2,17.0,2,0,0,55,True,0,1,2324,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29720,Wesley Okoduwa,DEF,Wolves,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,11,0,0,0,0,0,2204,0,2,0.0,0,414,145,40,False,0,38,2324,5,2
29721,Kevin Mbabu,DEF,Fulham,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,12,0,0,0,0,0,17658,4,2,0.0,0,0,127,40,False,0,38,2324,2,2
29722,Tyrell Malacia,DEF,Man Utd,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,5,0,0,0,0,0,2343,2,0,0.0,0,44,21,43,False,0,38,2324,3,3
29723,Daniel Gore,MID,Man Utd,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,5,0,0,0,0,0,575,2,0,0.0,0,0,3,45,False,0,38,2324,3,3
29724,Braian Ojeda Rodríguez,MID,Nott'm Forest,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,6,0,0,0,0,0,182,2,1,0.0,0,0,1,45,False,0,38,2324,2,2

In [131]:
for index, row in merged_fdr.iterrows():
    if row['was_home'] == True:
        # If was_home is True, swap team_a_score and team_h_score
        merged_fdr.at[index, 'team_player_score'] = row['team_h_score']
        merged_fdr.at[index, 'vs_score'] = row['team_a_score']
    else:
        # If was_home is False, swap team_a_score and team_h_score
        merged_fdr.at[index, 'vs_score'] = row['team_h_score']
        merged_fdr.at[index, 'team_player_score'] = row['team_a_score']

# Drop the original 'team_h_score' and 'team_a_score' columns
merged_fdr = merged_fdr.drop(columns=['team_h_score', 'team_a_score'])

In [132]:
merged_fdr['Price'] = merged_fdr['Price'].astype(float)/10

In [133]:
merged_fdr

,Player,Pos,Team_player,A,B,BPS,CS,C,xA,xGI,xG,xGC,GC,GS,ICT,I,kickoff_time,Mins,vs,OG,Pen_Miss,Pen_Save,RC,S,SB,T,Pts,Tran_In,Tran_Out,Price,was_home,YC,GW,season,Team_fdr,opponent_fdr,team_player_score,vs_score
0,Femi Seriki,DEF,Sheffield Utd,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,8,0,0,0,0,0,0,0.0,0,0,0,4.0,True,0,1,2324,2,2,0.0,1.0
1,Jack Hinshelwood,MID,Brighton,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,12,0,0,0,0,0,822,0.0,0,0,0,4.5,True,0,1,2324,2,3,4.0,1.0
2,Jadon Sancho,MID,Man Utd,0,0,4,0,11.3,0.05,0.05,0.00,1.08,0,0,2.3,3.8,2023-08-14T19:00:00Z,22,20,0,0,0,0,0,83993,8.0,1,0,0,7.0,True,0,1,2324,2,4,1.0,0.0
3,Rhys Norrington-Davies,DEF,Sheffield Utd,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,8,0,0,0,0,0,6456,0.0,0,0,0,4.0,True,0,1,2324,2,2,0.0,1.0
4,Vitaly Janelt,MID,Brentford,0,0,6,0,11.5,0.01,0.03,0.02,1.26,2,0,4.3,14.6,2023-08-13T13:00:00Z,90,18,0,0,0,0,0,6508,17.0,2,0,0,5.5,True,0,1,2324,3,2,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29720,Wesley Okoduwa,DEF,Wolves,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,11,0,0,0,0,0,2204,0.0,0,414,145,4.0,False,0,38,2324,5,2,0.0,2.0
29721,Kevin Mbabu,DEF,Fulham,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,12,0,0,0,0,0,17658,0.0,0,0,127,4.0,False,0,38,2324,2,2,4.0,2.0
29722,Tyrell Malacia,DEF,Man Utd,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,5,0,0,0,0,0,2343,0.0,0,44,21,4.3,False,0,38,2324,3,3,2.0,0.0
29723,Daniel Gore,MID,Man Utd,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,5,0,0,0,0,0,575,0.0,0,0,3,4.5,False,0,38,2324,3,3,2.0,0.0
29724,Braian Ojeda Rodríguez,MID,Nott'm Forest,0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,6,0,0,0,0,0,182,0.0,0,0,1,4.5,False,0,38,2324,2,2,2.0,1.0

In [134]:
merged_fdr = merged_fdr.merge(df_team[['short_name', 'name']], how='left', left_on='Team_player', right_on='name')

# Replace the 'Team_player' column with 'short_name'
merged_fdr['Team_player'] = merged_fdr['short_name']

# Drop the 'short_name' column after replacing
merged_fdr = merged_fdr.drop(columns=['short_name', 'name'])

In [135]:
merged_fdr = merged_fdr.merge(df_team[['short_name', 'id']], how='left', left_on='vs', right_on='id')

# Replace the 'vs' column with 'short_name'
merged_fdr['vs'] = merged_fdr['short_name']

# Drop the 'short_name' and 'name' columns after replacing
merged_fdr = merged_fdr.drop(columns=['short_name', 'id'])

In [136]:
def convert_opponent_string(df):
    df.loc[df['was_home'] == True, 'vs'] = df['vs'] + ' (A)'
    df.loc[df['was_home'] == False, 'vs'] = df['vs'] + ' (H)'
    df.loc[df['was_home'] == True, 'Team_player'] = df['Team_player'] + ' (H)'
    df.loc[df['was_home'] == False, 'Team_player'] = df['Team_player'] + ' (A)'
    return df

In [137]:
merged_home = pd.merge(merged_fdr, df_team[['short_name', 
                                                    'strength_overall_home', 
                                                    'strength_overall_away', 
                                                    'strength_attack_home', 
                                                    'strength_attack_away', 
                                                    'strength_defence_home', 
                                                    'strength_defence_away']],
                       left_on='Team_player', 
                       right_on='short_name', 
                       how='left')

# Merge for the opponent team
merged_opponent = pd.merge(merged_home, 
                            df_team[['short_name', 
                                       'strength_overall_home', 
                                       'strength_overall_away', 
                                       'strength_attack_home', 
                                       'strength_attack_away', 
                                       'strength_defence_home', 
                                       'strength_defence_away']],
                            left_on='vs', 
                            right_on='short_name', 
                            how='left', 
                            suffixes=('', '_opponent'))

# Optionally drop the 'short_name' columns for opponents if you don't need them
merged_opponent = merged_opponent.drop(columns=['short_name', 'short_name_opponent'])
merged_opponent=convert_opponent_string(merged_opponent)

In [138]:
merged_opponent

,Player,Pos,Team_player,A,B,BPS,CS,C,xA,xGI,xG,xGC,GC,GS,ICT,I,kickoff_time,Mins,vs,OG,Pen_Miss,Pen_Save,RC,S,SB,T,Pts,Tran_In,Tran_Out,Price,was_home,YC,GW,season,Team_fdr,opponent_fdr,team_player_score,vs_score,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,strength_overall_home_opponent,strength_overall_away_opponent,strength_attack_home_opponent,strength_attack_away_opponent,strength_defence_home_opponent,strength_defence_away_opponent
0,Femi Seriki,DEF,SHU (H),0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,CRY (A),0,0,0,0,0,0,0.0,0,0,0,4.0,True,0,1,2324,2,2,0.0,1.0,1030,1040,1045,1020,1020,1060,1070,1100,1080,1120,1060,1085
1,Jack Hinshelwood,MID,BHA (H),0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,LUT (A),0,0,0,0,0,822,0.0,0,0,0,4.5,True,0,1,2324,2,3,4.0,1.0,1100,1210,1070,1180,1135,1240,1055,1090,1020,1060,1090,1120
2,Jadon Sancho,MID,MUN (H),0,0,4,0,11.3,0.05,0.05,0.00,1.08,0,0,2.3,3.8,2023-08-14T19:00:00Z,22,WOL (A),0,0,0,0,0,83993,8.0,1,0,0,7.0,True,0,1,2324,2,4,1.0,0.0,1125,1220,1130,1210,1120,1230,1100,1100,1085,1105,1115,1100
3,Rhys Norrington-Davies,DEF,SHU (H),0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2023-08-12T14:00:00Z,0,CRY (A),0,0,0,0,0,6456,0.0,0,0,0,4.0,True,0,1,2324,2,2,0.0,1.0,1030,1040,1045,1020,1020,1060,1070,1100,1080,1120,1060,1085
4,Vitaly Janelt,MID,BRE (H),0,0,6,0,11.5,0.01,0.03,0.02,1.26,2,0,4.3,14.6,2023-08-13T13:00:00Z,90,TOT (A),0,0,0,0,0,6508,17.0,2,0,0,5.5,True,0,1,2324,3,2,2.0,2.0,1100,1100,1110,1055,1090,1150,1170,1230,1110,1150,1230,1310
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29720,Wesley Okoduwa,DEF,WOL (A),0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,LIV (H),0,0,0,0,0,2204,0.0,0,414,145,4.0,False,0,38,2324,5,2,0.0,2.0,1100,1100,1085,1105,1115,1100,1240,1370,1210,1350,1270,1390
29721,Kevin Mbabu,DEF,FUL (A),0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,LUT (H),0,0,0,0,0,17658,0.0,0,0,127,4.0,False,0,38,2324,2,2,4.0,2.0,1055,1175,1050,1180,1060,1170,1055,1090,1020,1060,1090,1120
29722,Tyrell Malacia,DEF,MUN (A),0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,BHA (H),0,0,0,0,0,2343,0.0,0,44,21,4.3,False,0,38,2324,3,3,2.0,0.0,1125,1220,1130,1210,1120,1230,1100,1210,1070,1180,1135,1240
29723,Daniel Gore,MID,MUN (A),0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,BHA (H),0,0,0,0,0,575,0.0,0,0,3,4.5,False,0,38,2324,3,3,2.0,0.0,1125,1220,1130,1210,1120,1230,1100,1210,1070,1180,1135,1240
29724,Braian Ojeda Rodríguez,MID,NFO (A),0,0,0,0,0.0,0.00,0.00,0.00,0.00,0,0,0.0,0.0,2024-05-19T15:00:00Z,0,BUR (H),0,0,0,0,0,182,0.0,0,0,1,4.5,False,0,38,2324,2,2,2.0,1.0,1065,1100,1050,1125,1080,1080,1045,1050,1050,1050,1040,1050

In [139]:
merged_opponent.to_csv(data_folder+'/clean_player_2324.csv', index=True)